name: elecxa
description: "Connecting local stores and customers."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.3.0
  location: ^7.0.0
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.png
    - assets/dev.jpg



